apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-container-deployment
  namespace: gke_cellular-tide-420012_us-central1-c_abc1-cluster #Build #120 names Namespace is required for apps/v1.Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-container
  template:
    metadata:
      labels:
        app: my-container
    spec:
      containers:
      - name: my-container
        image: "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"
        ports:
        - containerPort: 8080
