---
- name: Build & Deploy Docker Container
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"
        source: pull

    - name: Run Docker Container
      docker_container:
        name: my_container
        image: "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"
        state: started
        ports:
          - "8079:8080"
          
    - name: Gather Docker container facts
      docker_container:
        name: my_container
      register: container_facts

    - name: Print container facts
      debug:
        var: container_facts.containers

    - name: Apply Kubernetes manifest files #Ansible invoking the manifest files
      hosts: localhost
      tasks:
        - name: Apply Kubernetes manifest files
          k8s:
            state: present
            definition: "{{ item }}"
          with_items:
            - pod.yaml
            - service.yaml
            - deployment.yaml

