---
- name: Build & Deploy Docker Container
  hosts: 34.170.55.162
  gather_facts: false


  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"
        source: pull

    - name: Remove old Docker images
      docker_image:
        name: "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"
        state: absent
        before_image: "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"


    - name: Run Docker Container
      docker_container:
        name: my_container
        image: "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"
        state: started
        ports:
          - "8079:8080"
