---
- name: Build & Deploy Docker Container
  hosts: 34.170.55.162
  gather_facts: false
  log_path: /var/log/jenkins/ansible-playbook.log


  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"
        source: pull

    - name: Remove old Docker images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ docker_images.images | map(attribute='RepoTags') | flatten | select('match', '^{{ DOCKER_IMAGE }}:') | list }}"
      when: item != "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"
      ignore_errors: yes

    - name: Run Docker Container
      docker_container:
        name: my_container
        image: "{{ DOCKER_IMAGE }}:{{ BUILD_NUMBER }}"
        state: started
        ports:
          - "8079:8080"
