apiVersion: v1
kind: Service
metadata:
  name: my-container-service
spec:
  selector:
    app: my_container  # Labels used in deployment.yaml
  ports:
    - protocol: TCP
      port: 80  # Exposing the service on port 80 externally
      targetPort: 8079  # Forward traffic to port 8079 on the container
